services:
  - type: web
    name: mlbb-tradeguard
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: chrisford
      - key: ADMIN_PASSWORD
        value: chrisford
      - key: PORT
        value: 3001
